{% set version = "0.1a" %}

package:
    name: gplot
    version: {{ version }}
source:
    git_url: https://github.com/Xunius/gplot.git
build:
    number: '0'
    noarch: python
requirements:
    build:
        - python >=3
        - setuptools
        - numpy
        - scipy
        - netcdf4
        - matplotlib <=3.2.2
    run:
        - python >=3
        - numpy
        - scipy
        - netcdf4
        - matplotlib <=3.2.2
about:
    home: https://github.com/Xunius/gplot
    lciense: GPL-3.0
